import { Agent, User } from './types';

export const MOCK_USER: User = {
  username: 'addy',
  name: 'Aditya Singh',
  avatar: 'https://picsum.photos/seed/alex/200/200',
  bio: 'Building the future of autonomous systems. Lead Engineer at NeuralStack. Open source contributor.',
  followers: 0,
  following: 0,
  location: 'San Francisco, CA',
  website: 'https://alexrivera.dev',
  twitter: '@addy_ai',
};

const DEFAULT_ISSUES = [
  { id: '1', title: 'Performance degradation on long inputs', author: 'dev_guru', status: 'open' as const, createdAt: '2 days ago', commentsCount: 3 },
  { id: '2', title: 'Add support for French language', author: 'global_user', status: 'open' as const, createdAt: '5 days ago', commentsCount: 0 },
  { id: '3', title: 'Fix CSS hydration mismatch in sidebar', author: 'ui_expert', status: 'closed' as const, createdAt: '1 week ago', commentsCount: 12 },
];

const DEFAULT_PRS = [
  { id: '1', title: 'feat: Implement batch processing', author: 'speed_demon', status: 'open' as const, createdAt: '1 day ago' },
  { id: '2', title: 'fix: Correct regex for email validation', author: 'bug_hunter', status: 'merged' as const, createdAt: '3 days ago' },
];

export const MOCK_AGENTS: Agent[] = [
  {
    id: 'resume-analyzer',
    name: 'Resume Analyzer',
    owner: 'addy',
    ownerAvatar: 'https://picsum.photos/seed/addy/40/40',
    description: 'Detailed analysis of resumes with ATS optimization tips and interview preparation help.',
    tags: ['Career', 'HR', 'Analysis'],
    type: 'input-output',
    rating: 9.2,
    runs: '15.4k',
    stars: 842,
    forks: 156,
    issuesCount: 12,
    pullRequestsCount: 4,
    category: 'Career',
    updatedAt: '2 days ago',
    readme: `# Resume Analyzer 🚀\n\nMaximize your job search potential with our high-fidelity ATS optimization engine.\n\n### Key Features\n- **ATS Compatibility Scoring**: Instant feedback on how well your resume will perform in automated tracking systems.\n- **Keyword Optimization**: Automatic identification of missing technical and behavioral keywords.\n- **Section Analysis**: Deep dive into Experience, Projects, and Education formatting.\n- **PDF Support**: Direct parsing of professional PDF documents for realistic simulation.\n\n### How to Use\n1. Upload your PDF resume or paste the text content.\n2. Add optional context about the job you are targeting.\n3. Click "Run Agent" to see your score and actionable suggestions.\n\n*Pro Tip: Connect your Gemini API key to unlock deep behavioral analysis and custom interview questions tailored specifically to your profile.*`,
    promptTemplate: `Analyze this resume for ATS compatibility.`,
    configYaml: `name: Resume Analyzer\ntype: input-output\ncategory: Career`,
    metadataJson: `{"version": "1.0.0"}`,
    usageCode: `// Example usage\nconst response = await agent.run({ text: resumeText });`,
    issues: DEFAULT_ISSUES,
    pullRequests: DEFAULT_PRS,
  },
  {
    id: 'code-debugger-pro',
    name: 'Code Debugger Pro',
    owner: 'devraj',
    ownerAvatar: 'https://picsum.photos/seed/devraj/40/40',
    description: 'Expert level debugging across 20+ languages. Finds logical flaws and security vulnerabilities.',
    tags: ['Debugging', 'Coding', 'Security'],
    type: 'input-output',
    rating: 6.3,
    runs: '24.1k',
    stars: 1205,
    forks: 341,
    issuesCount: 42,
    pullRequestsCount: 12,
    category: 'Coding',
    updatedAt: '12 hours ago',
    readme: `# Code Debugger Pro 🛠️\n\nExpert-level syntax analysis and logical error detection for modern developers.\n\n### Capabilities\n- **Multi-language Support**: Specialized heuristics for Python, JavaScript, TypeScript, and more.\n- **Logical Flow Verification**: Detects hidden race conditions and edge cases that standard compilers miss.\n- **Strict Mode Enforcement**: Suggests modern best practices like strict equality and modular patterns.\n- **One-click Fixes**: Get the corrected code snippet ready to copy-paste into your IDE.\n\n### Why use Pro?\nWhile standard debuggers catch simple syntax errors, Pro uses advanced reasoning to identify architectural flaws that could cause production outages. It's like having a Senior Engineer reviewing every line of your code.`,
    promptTemplate: `Debug this code.`,
    configYaml: `name: Code Debugger Pro\ntype: input-output`,
    metadataJson: `{"version": "2.1.0"}`,
    usageCode: `// Example usage\nconst fix = await agent.run({ code: buggyCode });`,
    issues: DEFAULT_ISSUES,
    pullRequests: DEFAULT_PRS,
  },
  {
    id: 'linkedin-poster',
    name: 'LinkedIn Post Generator',
    owner: 'social_king',
    ownerAvatar: 'https://picsum.photos/seed/sk/40/40',
    description: 'Crafts viral-ready LinkedIn posts that drive engagement and network growth.',
    tags: ['Marketing', 'Social'],
    type: 'input-output',
    rating: 8.3,
    runs: '28k',
    stars: 340,
    forks: 45,
    issuesCount: 3,
    pullRequestsCount: 0,
    category: 'Social',
    updatedAt: '1 day ago',
    readme: `# LinkedIn Post Generator 📈\n\nTurn your raw ideas into high-engagement, viral-ready LinkedIn content in seconds.\n\n### Content Archetypes\n- **The Contrarian**: Challenge the status quo to spark debate and discussion.\n- **The Storyteller**: Build deep emotional connections through vulnerability and lessons learned.\n- **The Value-Driven**: Provide immediate actionable advice to build industry authority.\n\n### Features\n- **Auto-Hashtags**: Relevant hashtags generated for every post to maximize reach.\n- **Hook Variations**: Multiple hooks provided so you can A/B test your engagement.\n- **Visual Spacing**: Optimized for mobile reading with perfect line breaks and emojis.\n\n### Output Structure\nEach run generates a complete Post, a list of alternative Hooks, and a curated set of Hashtags.`,
    promptTemplate: `You are a social media growth hacker.`,
    configYaml: `name: LinkedIn Poster\ntype: input-output`,
    metadataJson: `{"version": "1.5.0"}`,
    usageCode: `// Transform your updates`,
    issues: DEFAULT_ISSUES,
    pullRequests: DEFAULT_PRS,
  },
  {
    id: 'research-agent',
    name: 'Research Agent',
    owner: 'addy',
    ownerAvatar: 'https://picsum.photos/seed/addy/40/40',
    description: 'Advanced multi-step reasoning engine for deep topic analysis and structured reporting.',
    tags: ['Analysis', 'Research', 'AI'],
    type: 'input-output',
    rating: 9.8,
    runs: '5.2k',
    stars: 2105,
    forks: 412,
    issuesCount: 5,
    pullRequestsCount: 2,
    category: 'Analysis',
    updatedAt: 'Just now',
    readme: `# Research Agent (Deep Engine) 🧠\n\nA multi-step reasoning system designed for deep topic understanding and structured, professional reporting.\n\n### Comprehensive Output Structure\n1. **Executive Summary**: Concise overview focusing on key takeaways.\n2. **Key Insights**: Sharp, valuable bullet points from 5-8 distinct perspectives.\n3. **Detailed Analysis**: Deep dive into Background, Landscape, Challenges, and Opportunities.\n4. **Real-World Examples**: 2-3 practical use-cases or industry examples.\n5. **Future Trends**: Forward-looking 3-5 year projections.\n6. **Conclusion**: Strong final takeaway and strategic advice.\n\n### Best Use Cases\n- **Strategic Intelligence**: Inform high-stakes business or technical decisions.\n- **Complex Domain Mapping**: Rapidly understand new tech or regulatory shifts.\n- **Trend Forecasting**: Identify "what's next" before it hits the mainstream.\n\n*This agent behaves like a senior analyst, providing depth and precision guaranteed by our master prompt architecture.*`,
    promptTemplate: `Conduct a deep research report on {{topic}}.`,
    configYaml: `name: Research Agent\ntype: input-output\ncategory: Analysis`,
    metadataJson: `{"version": "1.0.0"}`,
    usageCode: `const report = await agent.run({ query: "Future of AI" });`,
    issues: DEFAULT_ISSUES,
    pullRequests: DEFAULT_PRS,
  },
  {
    id: 'legal-summarizer',
    name: 'Legal Summarizer',
    owner: 'legal_bot',
    ownerAvatar: 'https://picsum.photos/seed/lb/40/40',
    description: 'Simplifies complex legal documents and contracts into easy-to-read executive summaries.',
    tags: ['Legal', 'Analysis'],
    type: 'input-output',
    rating: 9.3,
    runs: '9.2k',
    stars: 670,
    forks: 110,
    issuesCount: 8,
    pullRequestsCount: 2,
    category: 'Analysis',
    updatedAt: '1 day ago',
    readme: `# Legal Summarizer ⚖️\n\nProfessional contract analysis and risk assessment for complex agreements. Stop getting lost in legalese.\n\n### Core Features\n- **Risk Dashboard**: Color-coded categorization (Low, Medium, High) based on keyword density.\n- **Clause Detection**: Scans for liability, indemnity, penalties, and termination rights automatically.\n- **Executive Summaries**: Translates dense legal text into plain English for quick review.\n- **PDF Support**: Upload full contract documents for comprehensive scanning.\n\n### Safety First\nThis agent identifies "red flag" clauses like uncapped liability or non-competes, allowing you to focus your legal budget on the things that actually matter.\n\n*Note: This agent is an AI tool designed for informational purposes only and does not constitute official legal advice.*`,
    promptTemplate: `Analyze this contract for potential risks.`,
    configYaml: `name: Legal Summarizer\ntype: input-output`,
    metadataJson: `{"version": "2.2.0"}`,
    usageCode: `const report = await agent.run({ document: legalText });`,
    issues: DEFAULT_ISSUES,
    pullRequests: DEFAULT_PRS,
  },
  {
    id: 'resume-analyzer-devraj',
    name: 'Resume Analyzer',
    owner: 'devraj',
    ownerAvatar: 'https://picsum.photos/seed/devraj/40/40',
    description: 'Basic resume screening tool with focus on formatting and standard keyword matching.',
    tags: ['Career', 'Recruitment'],
    type: 'input-output',
    rating: 6.8,
    runs: '2.1k',
    stars: 124,
    forks: 12,
    issuesCount: 2,
    pullRequestsCount: 0,
    category: 'Career',
    updatedAt: '5 days ago',
    readme: `# Resume Screener\n\nA simple tool to check if your resume meets basic corporate standards for readability and formatting. This version focuses on essential keyword density and layout consistency.`,
    promptTemplate: `Check this resume for formatting issues.`,
    configYaml: `name: Resume Analyzer\ntype: input-output`,
    metadataJson: `{"version": "0.8.0"}`,
    usageCode: `// Simple check\nconst status = await agent.run({ content: text });`,
    issues: [],
    pullRequests: [],
  },
  {
    id: 'email-writer',
    name: 'Email Writer',
    owner: 'ai_master',
    ownerAvatar: 'https://picsum.photos/seed/aim/40/40',
    description: 'Crafts professional, persuasive emails for any scenario. Just describe the intent.',
    tags: ['Writing', 'Business'],
    type: 'chat',
    rating: 8.7,
    runs: '42k',
    stars: 560,
    forks: 89,
    issuesCount: 4,
    pullRequestsCount: 1,
    category: 'Business',
    updatedAt: '1 day ago',
    readme: `# Email Writer\n\nTalk to me to draft perfect cold emails, follow-ups, or resignation letters. Describe who you are writing to and what you want to achieve.`,
    promptTemplate: `You are a professional communications expert.`,
    configYaml: `name: Email Writer\ntype: chat`,
    metadataJson: `{"version": "1.2.0"}`,
    usageCode: `// Chat interface enabled`,
    issues: [],
    pullRequests: [],
  },
  {
    id: 'startup-idea-gen',
    name: 'Startup Idea Gen',
    owner: 'startupguru',
    ownerAvatar: 'https://picsum.photos/seed/sg/40/40',
    description: 'Generates high-potential startup ideas based on emerging market trends and tech gaps.',
    tags: ['Business', 'Innovation'],
    type: 'chat',
    rating: 9.4,
    runs: '18.2k',
    stars: 920,
    forks: 210,
    issuesCount: 8,
    pullRequestsCount: 3,
    category: 'Business',
    updatedAt: '3 days ago',
    readme: `# Startup Idea Generator\n\nDescribe a problem or industry to get unique business concepts. I specialize in identifying high-growth opportunities in tech and lifestyle sectors.`,
    promptTemplate: `You are a Silicon Valley venture capitalist.`,
    configYaml: `name: Startup Idea Generator\ntype: chat`,
    metadataJson: `{"version": "3.0.0"}`,
    usageCode: `// Start chatting to get ideas`,
    issues: [],
    pullRequests: [],
  },
  {
    id: 'blog-summarizer',
    name: 'Blog Summarizer',
    owner: 'datascientist',
    ownerAvatar: 'https://picsum.photos/seed/ds/40/40',
    description: 'Turns long blog posts into concise, 3-sentence summaries for quick consumption.',
    tags: ['Analysis', 'Writing'],
    type: 'input-output',
    rating: 8.9,
    runs: '55k',
    stars: 430,
    forks: 67,
    issuesCount: 2,
    pullRequestsCount: 1,
    category: 'Analysis',
    updatedAt: '5 hours ago',
    readme: `# Blog Summarizer\n\nPaste a long article to get the core takeaways instantly. Perfect for newsletters or social sharing.`,
    promptTemplate: `Summarize this text into exactly 3 sentences.`,
    configYaml: `name: Blog Summarizer\ntype: input-output`,
    metadataJson: `{"version": "1.0.5"}`,
    usageCode: `const summary = await agent.run({ text: longContent });`,
    issues: [],
    pullRequests: [],
  },
  {
    id: 'sql-query-gen',
    name: 'SQL Query Gen',
    owner: 'codewizard',
    ownerAvatar: 'https://picsum.photos/seed/cw/40/40',
    description: 'Translates natural language questions into perfect SQL queries for any database schema.',
    tags: ['Coding', 'Data'],
    type: 'chat',
    rating: 9.6,
    runs: '31k',
    stars: 1100,
    forks: 250,
    issuesCount: 15,
    pullRequestsCount: 7,
    category: 'Coding',
    updatedAt: '2 days ago',
    readme: `# SQL Generator\n\nAsk me questions like "Show me total sales by month" and get optimized SQL code for PostgreSQL, MySQL, or BigQuery.`,
    promptTemplate: `You are a database expert. Output only SQL code.`,
    configYaml: `name: SQL Generator\ntype: chat`,
    metadataJson: `{"version": "2.0.0"}`,
    usageCode: `// Ask in natural language`,
    issues: [],
    pullRequests: [],
  },
  {
    id: 'fitness-planner',
    name: 'Fitness Planner',
    owner: 'fitness_pro',
    ownerAvatar: 'https://picsum.photos/seed/fp/40/40',
    description: 'Customizes weekly workout routines based on your goals, equipment, and schedule.',
    tags: ['Health', 'Lifestyle'],
    type: 'chat',
    rating: 8.5,
    runs: '12k',
    stars: 210,
    forks: 34,
    issuesCount: 1,
    pullRequestsCount: 0,
    category: 'Lifestyle',
    updatedAt: '6 days ago',
    readme: `# Fitness Planner\n\nTell me your weight, height, and goal to get started. I create balanced routines including strength, cardio, and mobility.`,
    promptTemplate: `You are a certified personal trainer.`,
    configYaml: `name: Fitness Planner\ntype: chat`,
    metadataJson: `{"version": "1.0.0"}`,
    usageCode: `// Chat to build your plan`,
    issues: [],
    pullRequests: [],
  },
  {
    id: 'code-explainer',
    name: 'Code Explainer',
    owner: 'devraj',
    ownerAvatar: 'https://picsum.photos/seed/devraj/40/40',
    description: 'Step-by-step plain English explanations for complex code snippets and algorithms.',
    tags: ['Coding', 'Education'],
    type: 'input-output',
    rating: 9.5,
    runs: '38k',
    stars: 890,
    forks: 120,
    issuesCount: 10,
    pullRequestsCount: 5,
    category: 'Education',
    updatedAt: '4 hours ago',
    readme: `# Code Explainer\n\nPaste code to understand exactly how it works under the hood. Great for learning new libraries or onboarding to legacy codebases.`,
    promptTemplate: `Explain this code like I'm five.`,
    configYaml: `name: Code Explainer\ntype: input-output`,
    metadataJson: `{"version": "1.1.0"}`,
    usageCode: `const explanation = await agent.run({ code: complexCode });`,
    issues: [],
    pullRequests: [],
  },
  {
    id: 'cover-letter-gen',
    name: 'Cover Letter Gen',
    owner: 'addy',
    ownerAvatar: 'https://picsum.photos/seed/addy/40/40',
    description: 'Writes tailored cover letters by matching your skills to a specific job description.',
    tags: ['Career', 'Writing'],
    type: 'chat',
    rating: 8.8,
    runs: '19k',
    stars: 410,
    forks: 56,
    issuesCount: 2,
    pullRequestsCount: 1,
    category: 'Career',
    updatedAt: '3 days ago',
    readme: `# Cover Letter Wizard\n\nTell me about the job and your best skill. I draft professional, enthusiastic letters that stand out to hiring managers.`,
    promptTemplate: `You are a career coach.`,
    configYaml: `name: Cover Letter Gen\ntype: chat`,
    metadataJson: `{"version": "1.0.2"}`,
    usageCode: `// Chat to draft your letter`,
    issues: [],
    pullRequests: [],
  },
  {
    id: 'grammar-corrector',
    name: 'Grammar Corrector',
    owner: 'ml_engineer',
    ownerAvatar: 'https://picsum.photos/seed/mle/40/40',
    description: 'Instantly fixes typos and grammatical errors while preserving your unique voice.',
    tags: ['Writing', 'Education'],
    type: 'input-output',
    rating: 9.1,
    runs: '67k',
    stars: 320,
    forks: 23,
    issuesCount: 5,
    pullRequestsCount: 0,
    category: 'Education',
    updatedAt: '1 week ago',
    readme: `# Grammar Corrector\n\nPaste your text and I'll polish it for you. I fix punctuation, spelling, and tense issues without changing your original meaning.`,
    promptTemplate: `Fix grammar and spelling.`,
    configYaml: `name: Grammar Corrector\ntype: input-output`,
    metadataJson: `{"version": "2.0.1"}`,
    usageCode: `const cleanText = await agent.run({ text: messyText });`,
    issues: [],
    pullRequests: [],
  },
  {
    id: 'interview-coach',
    name: 'Interview Coach',
    owner: 'hr_guru',
    ownerAvatar: 'https://picsum.photos/seed/hr/40/40',
    description: 'Simulates high-stakes job interviews and provides real-time feedback on your answers.',
    tags: ['Career', 'HR'],
    type: 'chat',
    rating: 9.7,
    runs: '22k',
    stars: 980,
    forks: 180,
    issuesCount: 12,
    pullRequestsCount: 6,
    category: 'Career',
    updatedAt: '2 days ago',
    readme: `# AI Interview Coach\n\nSay "Start Interview" and tell me the role you're applying for. I'll ask challenging questions and grade your responses.`,
    promptTemplate: `You are a tough technical interviewer.`,
    configYaml: `name: Interview Coach\ntype: chat`,
    metadataJson: `{"version": "4.0.0"}`,
    usageCode: `// Start your mock interview`,
    issues: [],
    pullRequests: [],
  },
  {
    id: 'recipe-creator',
    name: 'Recipe Creator',
    owner: 'chef_ai',
    ownerAvatar: 'https://picsum.photos/seed/chef/40/40',
    description: 'Suggests delicious recipes based only on the ingredients you have in your fridge.',
    tags: ['Lifestyle', 'Food'],
    type: 'chat',
    rating: 8.4,
    runs: '15k',
    stars: 180,
    forks: 12,
    issuesCount: 0,
    pullRequestsCount: 0,
    category: 'Lifestyle',
    updatedAt: '5 days ago',
    readme: `# What's for Dinner?\n\nList your ingredients and I'll give you gourmet options. I can adjust for dietary restrictions and cooking time.`,
    promptTemplate: `You are a master chef.`,
    configYaml: `name: Recipe Creator\ntype: chat`,
    metadataJson: `{"version": "1.0.0"}`,
    usageCode: `// List ingredients in chat`,
    issues: [],
    pullRequests: [],
  },
  {
    id: 'travel-planner',
    name: 'Travel Planner',
    owner: 'nomad_ai',
    ownerAvatar: 'https://picsum.photos/seed/na/40/40',
    description: 'Builds the perfect multi-city travel itinerary based on your budget and interests.',
    tags: ['Lifestyle', 'Travel'],
    type: 'chat',
    rating: 8.6,
    runs: '14k',
    stars: 290,
    forks: 32,
    issuesCount: 2,
    pullRequestsCount: 0,
    category: 'Lifestyle',
    updatedAt: '3 days ago',
    readme: `# Global Explorer\n\nTell me where you want to go and for how long. I'll build a custom itinerary including flights, stays, and local secrets.`,
    promptTemplate: `You are a travel agent who has visited 100 countries.`,
    configYaml: `name: Travel Planner\ntype: chat`,
    metadataJson: `{"version": "1.3.0"}`,
    usageCode: `// Start planning your trip`,
    issues: [],
    pullRequests: [],
  },
];
